### ISSUE TITLE
rosjava_tools repository error:Setting up Android Studio & SDK with Ros

### ISSUE THREAD

**Issue by shehzi001** [rosjava/rosjava_build_tools#12]
Hello,

On this website there is a command that is using link from this repository.

=====================command========================
wstool init -j4 ~/rosjava/src https://raw.github.com/rosjava/rosjava_tools/hydro-devel/rosjava.rosinstall
# 

but i am unable to execute this command i am getting the following error.
# 

ERROR in config: Unable to download URL [https://raw.github.com/rosjava/rosjava_tools/hydro-devel/rosjava.rosinstall]: HTTP Error 404: Not Found
# 

Kindly let me know is the following link still correct or not??
https://raw.github.com/rosjava/rosjava_tools/hydro-devel/rosjava.rosinstall

Thanks

**Comment by stonier** [comment]
Where did you find that link? - looks like old documentation.

**Comment by stonier** [comment]
Closing this - reopen if there is new information.
