### ISSUE TITLE
rosjava with indigo and kitkat

### ISSUE THREAD

**Issue by Annyv2** [rosjava/rosjava_build_tools#25]
Hello,

I have installed rosjava from deb and from source (not knowing if this could case any issues) I've also installed android core but I have an error because I don't have the android 10 nor android 15 sdks. I would like to use rosjava with Ros Indigo on Ubuntu 14.04 on an android 19 (KitKat), is this possible? is there another option to connect a rosnode with android? for all I've seen it's only usable with Android 10 and android 15 but I have android v19.

Thanks in advance

**Comment by stonier** [comment]
You can have dependencies on libraries that are built with android 10 & android 15 even if you application is built with android 19. This is important to making sure those libraries are usable by applications targeting a variety of platforms. 

So...just install the 10 & 15 sdks so you can build older version libraries. Set your program to use 19. You should have no problem.
